/**
 * User API
 * API for managing users.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UserDTO {
    /**
    * Unique identifier for the user
    */
    'id': number;
    'firstName': string;
    'lastName': string;
    'email': string;
    'age': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "age",
            "baseName": "age",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserDTO.attributeTypeMap;
    }

    public constructor() {
    }
}

